# Generated by Django 3.0.5 on 2020-06-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.CharField(max_length=100)),
                ('Subsistema', models.CharField(max_length=100)),
                ('Datetime', models.CharField(max_length=100)),
                ('Demanda_Maxima_Instantanea_MW', models.CharField(max_length=100)),
                ('ENA_Bruta_MLT', models.CharField(max_length=100)),
                ('EAR_MAX_MWmes', models.CharField(max_length=100)),
                ('Carga_de_Energia_MWmed', models.CharField(max_length=100)),
                ('ENA_Bruta_MWmed', models.CharField(max_length=100)),
                ('Demanda_Maxima_horaria_MWh_h', models.CharField(max_length=100)),
                ('Geracao_de_Energia_dia_GWh', models.CharField(max_length=100)),
                ('Carga_de_Energia_GWh', models.CharField(max_length=100)),
                ('EAR_MWmes', models.CharField(max_length=100)),
                ('ENA_armazenavel_MWmed', models.CharField(max_length=100)),
                ('EAR_GWh', models.CharField(max_length=100)),
                ('Geracao_de_Energia_dia_MWmed', models.CharField(max_length=100)),
                ('ENA_armazenavel_MLT', models.CharField(max_length=100)),
                ('EAR', models.CharField(max_length=100)),
            ],
        ),
    ]
