# Generated by Django 3.0.5 on 2020-06-26 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gqlapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='Data',
        ),
    ]
